logsBucket: gs://reservation-457712-cloudbuild-logs
serviceAccount: cloudbuild-ci@reservation-457712.iam.gserviceaccount.com

timeout: 900s

substitutions:
  _REGION: us-east4
  _PROJ: reservation-457712

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: GCS_ONLY

# ── Build steps ───────────────────────────────────────────────────
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","${_REGION}-docker.pkg.dev/${_PROJ}/reservations/production","-f","apps/reservations/Dockerfile","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJ}/reservations/production"]

  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","${_REGION}-docker.pkg.dev/${_PROJ}/auth/production","-f","apps/auth/Dockerfile","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJ}/auth/production"]

  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","${_REGION}-docker.pkg.dev/${_PROJ}/notifications/production","-f","apps/notifications/Dockerfile","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJ}/notifications/production"]

  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","${_REGION}-docker.pkg.dev/${_PROJ}/payments/production","-f","apps/payments/Dockerfile","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJ}/payments/production"]

  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","${_REGION}-docker.pkg.dev/${_PROJ}/users/production","-f","apps/users/Dockerfile","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","${_REGION}-docker.pkg.dev/${_PROJ}/users/production"]
