apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/reservation-457712/auth/production
        name: auth
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwtSecret
          - name: JWT_EXPIRATION
            value: '3600'
          - name: TCP_PORT
            value: '3002'
          - name: HTTP_PORT
            value: '3003'
          - name: USERS_HOST
            value: users-tcp
          - name: USERS_PORT
            value: '3006'
        ports:
          - containerPort: 3002
          - containerPort: 3003
