apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users-http
spec:
  ports:
  - name: "http"
    port: 3007
    protocol: TCP
    targetPort: 3007
  selector:
    app: users
  type: NodePort
