apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users-tcp
spec:
  ports:
  - name: "tcp"
    port: 3006
    protocol: TCP
    targetPort: 3006
  selector:
    app: users
  type: ClusterIP
